var students = [
  // class 11A
  {
    "id": "5323",
    "name": "ខុម ស្រីដា",
    "gender": "ស្រី",
    "dob": "2009-08-02",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-226"
  },
  {
    "id": "5324",
    "name": "គង់ ស៊ីវនីត",
    "gender": "ស្រី",
    "dob": "2006-11-12",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-227"
  },
  {
    "id": "5325",
    "name": "ឃីម រ៉ានុន",
    "gender": "ប្រុស",
    "dob": "2008-10-25",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-228"
  },
  {
    "id": "5326",
    "name": "ងិន ស្រីដឿន",
    "gender": "ស្រី",
    "dob": "2008-04-14",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-229"
  },
  {
    "id": "5327",
    "name": "ងេន សម័យសុធា",
    "gender": "ប្រុស",
    "dob": "2008-06-27",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-230"
  },
  {
    "id": "5328",
    "name": "ចាន់ ផាន់សា",
    "gender": "ស្រី",
    "dob": "2007-06-03",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-231"
  },
  {
    "id": "5329",
    "name": "ចិន សៅពេជ",
    "gender": "ស្រី",
    "dob": "2006-03-06",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-232"
  },
  {
    "id": "5330",
    "name": "ជិញ ជាវអ៊ី",
    "gender": "ស្រី",
    "dob": "2008-05-01",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-233"
  },
  {
    "id": "5331",
    "name": "ជឿន ស្រីនិត",
    "gender": "ស្រី",
    "dob": "2008-09-08",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-234"
  },
  {
    "id": "5332",
    "name": "ញ៉ ស្រីណុំ",
    "gender": "ស្រី",
    "dob": "2009-03-18",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-235"
  },
  {
    "id": "5333",
    "name": "ញ៉ឹក ដាវី",
    "gender": "ស្រី",
    "dob": "2008-04-06",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-236"
  },
  {
    "id": "5334",
    "name": "តេង ចាន់ណេន",
    "gender": "ស្រី",
    "dob": "2007-12-22",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-237"
  },
  {
    "id": "5335",
    "name": "ថុល ស្រីថាវ",
    "gender": "ស្រី",
    "dob": "2008-01-24",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-238"
  },
  {
    "id": "5336",
    "name": "ទូច វិរៈ",
    "gender": "ប្រុស",
    "dob": "2008-08-07",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-239"
  },
  {
    "id": "5337",
    "name": "ទៀង ចាន់នូ",
    "gender": "ប្រុស",
    "dob": "2007-06-28",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-240"
  },
  {
    "id": "5338",
    "name": "ធំ តុលា",
    "gender": "ប្រុស",
    "dob": "2008-10-07",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-241"
  },
  {
    "id": "5339",
    "name": "ធី តាំងយូ",
    "gender": "ស្រី",
    "dob": "2008-10-01",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-242"
  },
  {
    "id": "5340",
    "name": "នៅ ស្រីមាន",
    "gender": "ស្រី",
    "dob": "2009-05-11",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-243"
  },
  {
    "id": "5341",
    "name": "បូរ៉ាន សៀវអ៊ិញ",
    "gender": "ស្រី",
    "dob": "2006-04-06",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-244"
  },
  {
    "id": "5342",
    "name": "ផល្លិត នីតា",
    "gender": "ស្រី",
    "dob": "2009-12-03",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-245"
  },
  {
    "id": "5343",
    "name": "ផាត ឆេង",
    "gender": "ស្រី",
    "dob": "2008-12-28",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-246"
  },
  {
    "id": "5344",
    "name": "ពូន ឡឹកណយ",
    "gender": "ស្រី",
    "dob": "2008-09-02",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-247"
  },
  {
    "id": "5345",
    "name": "ពូន សុខណា",
    "gender": "ប្រុស",
    "dob": "2007-01-12",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-248"
  },
  {
    "id": "5346",
    "name": "ពេជ្រ ចរណៃ",
    "gender": "ប្រុស",
    "dob": "2007-01-01",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-249"
  },
  {
    "id": "5347",
    "name": "ពេជ្រ សុខនទ្រីរ៉ាដា",
    "gender": "ស្រី",
    "dob": "2008-07-29",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-250"
  },
  {
    "id": "5348",
    "name": "ពៅ វត្តី",
    "gender": "ស្រី",
    "dob": "2009-04-21",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-251"
  },
  {
    "id": "5349",
    "name": "មាគ មេខា",
    "gender": "ប្រុស",
    "dob": "2008-09-26",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-252"
  },
  {
    "id": "5350",
    "name": "មឿន ស្រីទី",
    "gender": "ស្រី",
    "dob": "2006-09-12",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-253"
  },
  {
    "id": "5351",
    "name": "ម៉ៅ ស្រីយីង",
    "gender": "ស្រី",
    "dob": "2008-06-30",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-254"
  },
  {
    "id": "5352",
    "name": "យ៉ិន ចាន់ផល",
    "gender": "ប្រុស",
    "dob": "2007-10-10",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-255"
  },
  {
    "id": "5353",
    "name": "រ៉ាយ លីយ៉ា",
    "gender": "ស្រី",
    "dob": "2008-12-23",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-256"
  },
  {
    "id": "5354",
    "name": "លី រចនា",
    "gender": "ស្រី",
    "dob": "2008-01-04",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-257"
  },
  {
    "id": "5355",
    "name": "លី សៀងឡេង",
    "gender": "ប្រុស",
    "dob": "2009-10-01",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-258"
  },
  {
    "id": "5356",
    "name": "លី ឈិងប៉ាវ",
    "gender": "ប្រុស",
    "dob": "2009-12-22",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-259"
  },
  {
    "id": "5357",
    "name": "វ៉ា លីណាលីន",
    "gender": "ស្រី",
    "dob": "2008-07-15",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-260"
  },
  {
    "id": "5358",
    "name": "សន សៀវជី",
    "gender": "ស្រី",
    "dob": "2009-09-05",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-261"
  },
  {
    "id": "5359",
    "name": "សយ វិបុល",
    "gender": "ប្រុស",
    "dob": "2009-09-14",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-262"
  },
  {
    "id": "5360",
    "name": "សល់ ស្រីវីន",
    "gender": "ស្រី",
    "dob": "2007-06-07",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-263"
  },
  {
    "id": "5361",
    "name": "សាន់ សុនដេលី",
    "gender": "ប្រុស",
    "dob": "2010-06-20",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-264"
  },
  {
    "id": "5362",
    "name": "សាម ច័ន្ទកាន",
    "gender": "ប្រុស",
    "dob": "2007-08-02",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-265"
  },
  {
    "id": "5363",
    "name": "ស៊ីម សៅលីពីន",
    "gender": "ប្រុស",
    "dob": "2008-10-25",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-266"
  },
  {
    "id": "5364",
    "name": "សុខ ឡៃស៊ីញ",
    "gender": "ស្រី",
    "dob": "2007-05-08",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-267"
  },
  {
    "id": "5365",
    "name": "សុខធន វឌ្ឍន៍",
    "gender": "ប្រុស",
    "dob": "2010-03-15",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-268"
  },
  {
    "id": "5366",
    "name": "សឿន ផាន់នេត",
    "gender": "ប្រុស",
    "dob": "2007-03-19",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-269"
  },
  {
    "id": "5367",
    "name": "ហាក់ ជីលីន",
    "gender": "ស្រី",
    "dob": "2008-01-01",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-270"
  },
  {
    "id": "5368",
    "name": "ហួម សុខសុភា",
    "gender": "ប្រុស",
    "dob": "2008-06-05",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-271"
  },
  {
    "id": "5369",
    "name": "ហេង រេនប៊ី",
    "gender": "ប្រុស",
    "dob": "2009-03-31",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-272"
  },
  {
    "id": "5370",
    "name": "ឡេង ស៊ូ",
    "gender": "ស្រី",
    "dob": "2006-06-02",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-273"
  },
  {
    "id": "6656",
    "name": "ឡុង សុខាវល័ក្ខ",
    "gender": "ស្រី",
    "dob": "2007-12-26",
    "class": "11A",
    "address": "ស្រុក កំរៀង",
    "photo": "001.jpg",
    "phone": "N/A",
    "father": "….",
    "mother": "….",
    "studyYear": "2025-274"
  }
]
